/**
 * This class is generated by jOOQ
 */
package com.jmdm.server;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table devices
	 */
	public static final com.jmdm.server.tables.Devices DEVICES = com.jmdm.server.tables.Devices.DEVICES;

	/**
	 * The table user_types
	 */
	public static final com.jmdm.server.tables.UserTypes USER_TYPES = com.jmdm.server.tables.UserTypes.USER_TYPES;

	/**
	 * The table users
	 */
	public static final com.jmdm.server.tables.Users USERS = com.jmdm.server.tables.Users.USERS;
}
