/**
 * This class is generated by jOOQ
 */
package com.jmdm.server.entities;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.DevicesRecord> PK_DEVICES = UniqueKeys0.PK_DEVICES;
	public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.UserTypesRecord> PK_USER_TYPES = UniqueKeys0.PK_USER_TYPES;
	public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.UsersRecord> PK_USERS = UniqueKeys0.PK_USERS;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.DevicesRecord, com.jmdm.server.entities.tables.records.UsersRecord> FK_DEVICES_USERS_1 = ForeignKeys0.FK_DEVICES_USERS_1;
	public static final org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.UsersRecord, com.jmdm.server.entities.tables.records.UserTypesRecord> FK_USERS_USER_TYPES_1 = ForeignKeys0.FK_USERS_USER_TYPES_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.DevicesRecord> PK_DEVICES = createUniqueKey(com.jmdm.server.entities.tables.Devices.DEVICES, com.jmdm.server.entities.tables.Devices.DEVICES.ID);
		public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.UserTypesRecord> PK_USER_TYPES = createUniqueKey(com.jmdm.server.entities.tables.UserTypes.USER_TYPES, com.jmdm.server.entities.tables.UserTypes.USER_TYPES.ID);
		public static final org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.UsersRecord> PK_USERS = createUniqueKey(com.jmdm.server.entities.tables.Users.USERS, com.jmdm.server.entities.tables.Users.USERS.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.DevicesRecord, com.jmdm.server.entities.tables.records.UsersRecord> FK_DEVICES_USERS_1 = createForeignKey(com.jmdm.server.entities.Keys.PK_USERS, com.jmdm.server.entities.tables.Devices.DEVICES, com.jmdm.server.entities.tables.Devices.DEVICES.USER_ID);
		public static final org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.UsersRecord, com.jmdm.server.entities.tables.records.UserTypesRecord> FK_USERS_USER_TYPES_1 = createForeignKey(com.jmdm.server.entities.Keys.PK_USER_TYPES, com.jmdm.server.entities.tables.Users.USERS, com.jmdm.server.entities.tables.Users.USERS.USER_TYPE_ID);
	}
}
