/**
 * This class is generated by jOOQ
 */
package com.jmdm.server.entities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devices extends org.jooq.impl.TableImpl<com.jmdm.server.entities.tables.records.DevicesRecord> {

	private static final long serialVersionUID = 1187743457;

	/**
	 * The singleton instance of <code>devices</code>
	 */
	public static final com.jmdm.server.entities.tables.Devices DEVICES = new com.jmdm.server.entities.tables.Devices();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jmdm.server.entities.tables.records.DevicesRecord> getRecordType() {
		return com.jmdm.server.entities.tables.records.DevicesRecord.class;
	}

	/**
	 * The column <code>devices.id</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.entities.tables.records.DevicesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>devices.imei</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.entities.tables.records.DevicesRecord, java.lang.String> IMEI = createField("imei", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>devices.location</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.entities.tables.records.DevicesRecord, java.lang.String> LOCATION = createField("location", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>devices.user_id</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.entities.tables.records.DevicesRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>devices</code> table reference
	 */
	public Devices() {
		this("devices", null);
	}

	/**
	 * Create an aliased <code>devices</code> table reference
	 */
	public Devices(java.lang.String alias) {
		this(alias, com.jmdm.server.entities.tables.Devices.DEVICES);
	}

	private Devices(java.lang.String alias, org.jooq.Table<com.jmdm.server.entities.tables.records.DevicesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Devices(java.lang.String alias, org.jooq.Table<com.jmdm.server.entities.tables.records.DevicesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jmdm.server.entities.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.DevicesRecord> getPrimaryKey() {
		return com.jmdm.server.entities.Keys.PK_DEVICES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.DevicesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jmdm.server.entities.tables.records.DevicesRecord>>asList(com.jmdm.server.entities.Keys.PK_DEVICES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.DevicesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.jmdm.server.entities.tables.records.DevicesRecord, ?>>asList(com.jmdm.server.entities.Keys.FK_DEVICES_USERS_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jmdm.server.entities.tables.Devices as(java.lang.String alias) {
		return new com.jmdm.server.entities.tables.Devices(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jmdm.server.entities.tables.Devices rename(java.lang.String name) {
		return new com.jmdm.server.entities.tables.Devices(name, null);
	}
}
