/**
 * This class is generated by jOOQ
 */
package com.jmdm.server.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTypes extends org.jooq.impl.TableImpl<com.jmdm.server.tables.records.UserTypesRecord> {

	private static final long serialVersionUID = -1356630337;

	/**
	 * The singleton instance of <code>user_types</code>
	 */
	public static final com.jmdm.server.tables.UserTypes USER_TYPES = new com.jmdm.server.tables.UserTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jmdm.server.tables.records.UserTypesRecord> getRecordType() {
		return com.jmdm.server.tables.records.UserTypesRecord.class;
	}

	/**
	 * The column <code>user_types.id</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UserTypesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>user_types.type_name</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UserTypesRecord, java.lang.String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>user_types</code> table reference
	 */
	public UserTypes() {
		this("user_types", null);
	}

	/**
	 * Create an aliased <code>user_types</code> table reference
	 */
	public UserTypes(java.lang.String alias) {
		this(alias, com.jmdm.server.tables.UserTypes.USER_TYPES);
	}

	private UserTypes(java.lang.String alias, org.jooq.Table<com.jmdm.server.tables.records.UserTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserTypes(java.lang.String alias, org.jooq.Table<com.jmdm.server.tables.records.UserTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jmdm.server.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jmdm.server.tables.records.UserTypesRecord> getPrimaryKey() {
		return com.jmdm.server.Keys.PK_USER_TYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jmdm.server.tables.records.UserTypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jmdm.server.tables.records.UserTypesRecord>>asList(com.jmdm.server.Keys.PK_USER_TYPES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jmdm.server.tables.UserTypes as(java.lang.String alias) {
		return new com.jmdm.server.tables.UserTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jmdm.server.tables.UserTypes rename(java.lang.String name) {
		return new com.jmdm.server.tables.UserTypes(name, null);
	}
}
