/**
 * This class is generated by jOOQ
 */
package com.jmdm.server.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<com.jmdm.server.tables.records.UsersRecord> {

	private static final long serialVersionUID = 1782832714;

	/**
	 * The singleton instance of <code>users</code>
	 */
	public static final com.jmdm.server.tables.Users USERS = new com.jmdm.server.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jmdm.server.tables.records.UsersRecord> getRecordType() {
		return com.jmdm.server.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>users.id</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UsersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>users.username</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UsersRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>users.password</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>users.company</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UsersRecord, java.lang.String> COMPANY = createField("company", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>users.user_type_id</code>.
	 */
	public final org.jooq.TableField<com.jmdm.server.tables.records.UsersRecord, java.lang.Integer> USER_TYPE_ID = createField("user_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, com.jmdm.server.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.jmdm.server.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.jmdm.server.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jmdm.server.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jmdm.server.tables.records.UsersRecord> getPrimaryKey() {
		return com.jmdm.server.Keys.PK_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jmdm.server.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jmdm.server.tables.records.UsersRecord>>asList(com.jmdm.server.Keys.PK_USERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.jmdm.server.tables.records.UsersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.jmdm.server.tables.records.UsersRecord, ?>>asList(com.jmdm.server.Keys.FK_USERS_USER_TYPES_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jmdm.server.tables.Users as(java.lang.String alias) {
		return new com.jmdm.server.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jmdm.server.tables.Users rename(java.lang.String name) {
		return new com.jmdm.server.tables.Users(name, null);
	}
}
